# Ansible Playbook
# Name: Updates
# Descriptie: Het installeren van updates op de Windows Server
# Auteur: Sebastiaan & Michel
# Versie: 1.0
# Notes: Dit playbook heeft 3 opties waaruit je kan kiezen. 

- name: "Installeer alle security, critical & rollup updates"
  ansible.windows.win_updates:
   category_names:
     - SecurityUpdates
     - CriticalUpdates
     - UpdateRollups
   reboot: true
   reboot_timeout: 3600

- name: "Installeer ALLE updates"
  ansible.windows.win_updates:
    category_names: '*'
    reboot: true
    reboot_timeout: 3600

- name: "Installeer updates met code"
  ansible.windows.win_updates:
   category_names:
   - SecurityUpdates
   - CriticalUpdates
   - UpdateRollups
   accept_list: 
   - KB2267602
   - KB5030178
   - KB890830
   - KB5030214
   reboot: true
   reboot_timeout: 3600

- name: Reboot de server
  ansible.windows.win_reboot: