- hosts: LinuxServer
  gather_facts: true
  become: true
  roles:
  - { role: docker, tags: [ 'docker']}
  - { role: ntp, tags: [ 'ntp']}

- hosts: routers 
  gather_facts: true
  become: true
  roles:
  - { role: routers, tags: [ 'routers']}

- hosts: switches
  gather_facts: true
  become: true
  roles:
  - { role: switches, tags: [ 'switches']}

- hosts: WindowsServer
  gather_facts: true
  become: yes
  become_method: runas
  become_user: Administrator
  roles:
  - { role: windows, tags: [ 'windows']}
  - { role: windows updates, tags: [ 'updates']}

- hosts: Werkstations
  gather_facts: true
  become: yes
  become_method: runas
  become_user: Administrator
  roles:
  - { role: werkstations, tags: [ 'werkstations']}
