- hosts: LinuxServer
  gather_facts: true
  become: true
  roles:
#  - { role: linux/backup, tags: [ 'linux_backup']}
  - { role: linux/bash, tags: [ 'linux_bash']}
  - { role: containers/docker, tags: [ 'docker']}
  - { role: linux/basic, tags: [ 'basic']}
  - { role: linux/firewall, tags: [ 'linux_firewall']}
  - { role: linux/ntp, tags: [  'linux_ntp']}
  - { role: linux/restore,  tags: [ 'linux_restore']}
  - { role: linux/users, tags:  [ 'linux_users']}


- hosts: routers 
  gather_facts: true
  become: true
  roles:
  - { role: networking/routers, tags: [ 'routers']}

- hosts: switches
  gather_facts: true
  become: true
  roles:
  - { role: networking/switches, tags: [ 'switches']}

- hosts: WindowsServer
  gather_facts: true
  become: yes
  become_method: runas
  become_user: Administrator
  roles:
  - { role: windows/, tags: [ 'alles']}
  - { role: windows/basic, tags: [ 'basic']}
  - { role: windows/adds, tags: [ 'adds']}
  - { role: windows/agdlp, tags: [ 'agdlp']}
  - { role: windows/backup, tags: [ 'backup']}
  - { role: windows/dhcp, tags: [ 'dhcp']}
  - { role: windows/dns,  tags: [ 'dns']}
  - { role: windows/firewall, tags: [ 'firewall']}
  - { role: windows/gpo,  tags: [ 'gpo']}
  - { role: windows/ou, tags: [ 'ou']}
  - { role: windows/restore, tags: [ 'restore']}
  - { role: windows/shares, tags: [ 'shares']}
  - { role: windows/ssh, tags: [ 'ssh']}
  - { role: windows/users, tags: [ 'users']}
  - { role: windows/updates, tags: [ 'updates']}

- hosts: Werkstations
  gather_facts: true
  become: yes
  become_method: runas
  become_user: sebastiaan
  roles:
  - { role: werkstations/domain, tags: [ 'domain']}
  - { role: werkstations/apps, tags: [ 'apps']}
  - { role: werkstations/ai_nvidia, tags: [ 'nvidia']}
  - { role: werkstations/ai_amd, tags: [ 'amd']}