- name: Generate SSH key pair if not exists
  command: ssh-keygen -t rsa -b 2048 -N "" -f /home/sebastiaan/.ssh/id_rsa
  args:
    creates: /home/sebastiaan/.ssh/id_rsa

- name: Copy SSH key to Debian machine
  become: yes
  command: ssh-copy-id -i /home/sebastiaan/.ssh/id_rsa.pub -f sebastiaan@debian
  args:
    creates: /home/sebastiaan/.ssh/authorized_keys
  ignore_errors: yes

- name: Looking if Rsync is installed
  apt:
    name: rsync
    state: present
    update_cache: true

- name: Create a directory for the rsync script
  file:
    path: /scripts
    state: directory
    mode: 0777
    owner: root
    group: root

- name: Copy rsync.sh[push] to the remote server
  copy:
    src: templates/rsync.j2
    dest: /scripts/rsync.sh
    mode: 0777
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Execute rsync.sh script on the remote server
  ansible.builtin.script: /scripts/rsync.sh
  #   remote_src: yes
  # become: yes


- name: Display the script output
  debug:
    var: fetch_result
