# Tijdens het zoeken naar SSH security kwam ik uit op (https://www.sshguard.net/faq.html) SSHGuard. Ik ben van plan dit te
# gebruiken voor SSH System Hardening. Zie link naar FAQ.

# https://github.com/nephosolutions/ansible-role-sshguard/blob/master/defaults/main.yaml

- name: Pak SSHGuard tar.gz
  ansible.builtin.get_url:
    url: https://sourceforge.net/projects/sshguard/files/sshguard/2.4.2/sshguard-2.4.2.tar.gz/download
    dest: /etc/
  register: download_result

- name: Extract SSHGuard into /etc/
  ansible.builtin.unarchive:
    src: /etc/sshguard-2.4.2.tar.gz
    dest: /etc/
    remote_src: true
  when: download_result.changed


- name: Configure and compile SSHGuard (replace with actual commands)
  command: ./configure && make && make install
  args:
    chdir: /etc/sshguard-2.4.2
  when: download_result.changed

- name: Configure sshguard and whitelist from templates
  template:
    src: "templates/{{ item }}.j2"
    dest: "{{ sshguard_config_path }}/{{ item }}"
    owner: root
    group: root
    mode: '0644'
    remote_src: true
  with_items:
    - sshguard.conf
  notify: restart sshguard service
  when: download_result.changed  # Only configure if SSHGuard was downloaded and extracted

- name: restart sshguard service
  service:
    name: "{{ sshguard_service }}"
    state: restarted
  when: download_result.changed  # Only restart if SSHGuard was configured


