# Tijdens het zoeken naar SSH security kwam ik uit op (https://www.sshguard.net/faq.html) SSHGuard. Ik ben van plan dit te
# gebruiken voor SSH System Hardening. Zie link naar FAQ.

# https://github.com/nephosolutions/ansible-role-sshguard/blob/master/defaults/main.yaml

- name: Pak SSHGuard tar.gz
  ansible.builtin.get_url:
    url: https://sourceforge.net/projects/sshguard/files/sshguard/2.4.2/sshguard-2.4.2.tar.gz/download
    dest: /etc/

- name: Extract SSHGuard into /etc/
  ansible.builtin.unarchive:
    src: /etc/sshguard-2.4.2.tar.gz
    dest: /etc/
    remote_src: true

# ./configure ?? 


- name: Configure sshguard and whitelist from templates
  template:
    src: "templates/{{ item }}.j2" # waar staat de file
    dest: "{{ sshguard_config_path }}/{{ item }}" # waar staat de file 
    owner: root # wie de eigenenaar is
    group: root # welke groep
    mode: '0644' # welke rechten
    remote_src: true # kijkt op het remote is
  with_items: 
    - sshguard.conf
    - whitelist
  notify: restart sshguard service


- name: restart sshguard service
  service:
    name: "{{ sshguard_service }}"
    state: restarted

