- name: Install Prerequisites
  apt: name=aptitude update_cache=yes state=latest force_apt_get=yes

# Sudo Group Setup
- name: "Installeer sudo"
  ansible.builtin.package:
    pkg: "sudo"
    state: present

- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

# Install Packages
- name: Update apt
  apt: update_cache=yes

- name: Install required system packages
  apt: name={{ sys_packages }} state=latest
