# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html

- name: Create multiple users
  user:
    name: "{{ item.username }}"
    password: Welkom01!
  with_items: "{{ users }}"

- name: Create a 2048-bit SSH key for multiple users in ~{user}/.ssh/id_rsa
  ansible.builtin.user:
    name: "{{ item.username }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  with_items: "{{ users }}"
