- name: Get root user info
  ansible.builtin.getent:
    database: passwd
    key: "{{ item.username}}" 
- ansible.builtin.debug:
    var: ansible_facts.getent_passwd

- name: Create users 
  present: yes
  user:
    name: "{{ item.username }}"
    password: "{{ item.password | password_hash('sha512') }}"
    createhome: yes # Deze parameter zorgt ervoor dat een home directory wordt aangemaakt
    shell: /bin/bash 
  with_items: "{{ users }}" # Hier wordt de variabele users gebruikt
  # when:

- name: Add sudoers users to the wheel group
  user:
    name: "{{ item.username }}"
    groups: wheel
    append: yes
    state: present
    createhome: yes
  with_items: "{{ users }}"
  when: item.username in (ansible_facts.ansible_users | default([]) | map(attribute='name') | list)

- name: Create a 2048-bit SSH key for multiple users in ~{user}/.ssh/id_rsa
  ansible.builtin.user:
    name: "{{ item.username }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  with_items: "{{ users }}"
  when: item.username in (ansible_facts.ansible_users | default([]) | map(attribute='name') | list)