# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html

- name: Create multiple users with custom home directories
  present: yes
  user:
    name: "{{ item.username }}" # Hier wordt de gebruikersnaam ingesteld
    password: "{{ item.password | password_hash('sha512') }}" # Deze parameter zorgt ervoor dat het wachtwoord wordt gehashed
    group: root # Deze parameter zorgt ervoor dat de gebruiker in de root groep wordt geplaatst
    createhome: true # Deze parameter zorgt ervoor dat een home directory wordt aangemaakt
    shell: /bin/bash
  with_items: "{{ users }}" # Hier wordt de variabele users gebruikt

- name: Add sudoers users to wheel group
  user:
    name: "{{ item.username }}"
    groups: wheel
    append: yes
    state: present
    createhome: yes
  with_items: "{{ users }}" # Hier wordt de variabele users gebruikt


- name: Create a 2048-bit SSH key for multiple users in ~{user}/.ssh/id_rsa
  ansible.builtin.user:
    name: "{{ item.username }}"
    generate_ssh_key: yes # Deze parameter zorgt ervoor dat er een SSH key wordt gegenereerd
    ssh_key_bits: 2048 
    ssh_key_file: .ssh/id_rsa
  with_items: "{{ users }}" 
