- name: Installeer OpenSSH.client
  ansible.windows.win_powershell:
    script: |
      if (!(Get-WindowsCapability -Online | Where-Object Name -like 'OpenSSH*')) {
        Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0
      } 


- name: Installeer OpenSSH.server en start de service
  ansible.windows.win_powershell:
    script: |
        Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
        Start-Service sshd
        Set-Service -Name sshd -StartupType 'Automatic' 

- name: pas de Remote Desktop settings aan
  ansible.windows.win_powershell:
    script: |
      Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
      Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "AllowTSConnections" -Value 1
  register: remote_desktop_result

- name: herstart de Remote Desktop service
  win_reboot:
  when: remote_desktop_result is changed