- name: Disable Port Security on all interfaces
  ios_config:
    lines:
      - interface range {{ item.value.port }}
      - no switchport port-security violation restrict
      - no switchport port-security
  register: port_security_config
  loop: "{{ ports | dict2items }}"

- name: Shutdown ports with no connectivity
  ios_config:
    lines:
      - no spanning-tree portfast bpduguard default
      - no errdisable recovery cause all
      - no errdisable recovery interval 30
      - no errdisable detect cause all
      - no errdisable detect cause link-flap
  register: shutdown_ports_config

- name: Disable Port violation on all interfaces
  ios_config:
    lines:
      - interface range {{ item.value.port }}
      - no switchport port-security mac-address sticky
  register: sticky_mac_config
  loop: "{{ ports | dict2items }}"

- name: Configure Blackhole VLAN
  ios_config:
    lines:
      - no vlan {{ blackhole_vlan_id }}
      - interface range {{ item.value.port }}
      - no switchport access vlan {{ blackhole_vlan_id }}
      - no shutdown
  register: blackhole_vlan_config
  loop: "{{ ports | dict2items }}"

- name: Save configuration
  ios_config:
    save_when: always
  register: output
