# Dit werkt alleen op Linux

- name: Kopieer systeeminfo.sh naar de target
  copy:
    src: roles/linux/bash/tasks/systeeminfo.sh
    dest: /tmp/systeeminfo.sh
    mode: 0770
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Voer systeeminfo.sh uit op de target
  shell:
    chdir: /tmp
    cmd: ./systeeminfo.sh
  register: fetch_result


- name: Geef de output weer op de ansible controller
  debug: 
    var: fetch_result
