- name: "Maak de groep 'Gebruikers' aan"
  group:
    name: Gebruikers
    state: present   

- name: "Maak user groeps aan"
  group:
    name: "{{ item.key }}"
    state: present
  with_items: "{{ Gebruikers }}"

- name: "Maak users aan in de groep 'Gebruikers', ook met homefolder & wachtwoord"
  user:
    name: "{{ item.key }}"
    groups: Gebruikers,{{ item.key }}
    append: true
    state: present
    shell: /bin/bash
    createhome: yes
    password: "{{ item.value.password | password_hash('sha512') }}"
  with_items: "{{ Gebruikers }}"
  changed_when: false

- name: "Permissies aanpassen voor de homefolders"
  ansible.builtin.file:
    path: /home/{{item.key}}
    state: directory
    recurse: yes
    owner: "{{item.key}}"
    group: "{{item.key}}"
    mode: '0770'
  with_items: "{{ Gebruikers }}"
