ansible_host: 192.168.199.154

__ntp_daemon: ntp
ntp_tzdata_package: tzdata
__ntp_package: ntp
__ntp_config_file: /etc/ntp.conf
__ntp_driftfile: /var/lib/ntp/drift
ntp_cron_daemon: cron

ntp_enabled: true
ntp_timezone: Etc/UTC

# ntp_daemon: [various]
# ntp_package: ntp
# ntp_config_file: /etc/ntp.conf
# ntp_driftfile: [various]

ntp_manage_config: true

# NTP server area configuration (leave empty for 'Worldwide').
# See: http://support.ntp.org/bin/view/Servers/NTPPoolServers
ntp_area: 'nl'
ntp_servers:
  - "0{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
  - "1{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
  - "2{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
  - "3{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"

ntp_restrict:
  - "127.0.0.1"
  - "::1"

ntp_cron_handler_enabled: false
ntp_tinker_panic: true

Gebruikers:
  - key: "Michel"
    value:
      name: "Michel"
      password: "{{ user_password }}"
  - key: "Administrator"
    value:
      name: "Administrator"
      password: "{{ user_password }}"
  - key: "Maid"
    value:
      name: "Maid"
      password: "{{ user_password }}"
  - key: "Andy"
    value:
      name: "Andy"
      password: "{{ user_password }}"
  - key: "Joshua"
    value:
      name: "Joshua"
      password: "{{ user_password }}"


# SSH
ssh_port: "22"
ssh_max_auth_tries: "6"
git remote set-url origin https://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@github.com/Pueriles/Ansible-Advanced-Fork