---
create_user: user
hostname: debian
copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
sys_packages: [ 'curl', 'vim', 'git', 'ufw', 'firewalld', 'ncdu']

# user.yml
users:
  - username: sebas
    password: Welkom01!
  - username: michel
    password: Welkom01!
  - username: andy
    password: Welkom01!
  - username: maid
    password: Welkom01!
  - username: joshua
    password: Welkom01!

# sshGuard
sshguard_block_time: 120
sshguard_detection_time: 1800
sshguard_threshold: 30

sshguard_config_items:
  - sshguard.conf
  - whitelist

jinja:
  - sshguard.conf
  - whitelist


sshguard_config_path: /etc/sshguard-2.4.2
sshguard_service: sshguard
sshguard_service_enabled: yes
sshguard_service_state: started

sshguard_whitelist:
  - comment: IPv4 localhost
    address: 127.0.0.0/8

# NTP
__ntp_daemon: ntp
ntp_tzdata_package: tzdata
__ntp_package: ntp
__ntp_config_file: /etc/ntp.conf
__ntp_driftfile: /var/lib/ntp/drift
ntp_cron_daemon: cron

ntp_enabled: true
ntp_timezone: Etc/UTC

# ntp_daemon: [various]
# ntp_package: ntp
# ntp_config_file: /etc/ntp.conf
# ntp_driftfile: [various]

ntp_manage_config: true

# NTP server area configuration (leave empty for 'Worldwide').
# See: http://support.ntp.org/bin/view/Servers/NTPPoolServers
ntp_area: 'nl'
ntp_servers:
  - "0{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
  - "1{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
  - "2{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
  - "3{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"

ntp_restrict:
  - "127.0.0.1"
  - "::1"

ntp_cron_handler_enabled: false

ntp_tinker_panic: true